### ISSUE TITLE
Make better use of table formatting 

### ISSUE THREAD

**Issue by bslassey** [bslassey/tigress-threat-model#10]
As discussed in @dkg's review https://mailarchive.ietf.org/arch/msg/tigress/NlwVk1XCcAkwNnSDj6c33vgZvhU/

>   Tables are a poor fit for the kind of narrative discussion in the two
>   "Threat Description" tables.  I understand the appeal of being able
>   to scan the scenarios in summarized form, but i think you can do
>   both: for each scenario:
> 
> - give it a short, catchy name;
> 
> - move the description of its mitigations into its own subsection with
>   the short name
> 
> - keep the table, but the columns are now: name, likelihood, impact,
>   reference (where reference is a pointer to the relevant subsection.

**Comment by snorp** [comment]
Fixed by #13
