### ISSUE TITLE
Clarify share invitation vs share request

### ISSUE THREAD

**Issue by bslassey** [bslassey/tigress-threat-model#8]
As discussed in @dkg's review https://mailarchive.ietf.org/arch/msg/tigress/NlwVk1XCcAkwNnSDj6c33vgZvhU/

>   the "Functional Goals" section refers to a "share request" but the
>   "assets and data" section refers to a "share invitation".  if these
>   are the same thing, please use the same term.  If they're different
>   things, please explain the difference.

**Comment by snorp** [comment]
This doesn't seem to apply any more. There are no instances of "share request" in the current document.
